### ISSUE TITLE
Ingester flush queue is backing up again

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/cortex#254]
Things we should do to help:
- [x] add table name as dimension to the the dynamodb errors metrics (#256)
- [x] limit number of retries for chunk flush on provisioned throughput errors (#256)
- [x] add alert when avg number of chunks/series > 1.5  (https://github.com/weaveworks/service-conf/pull/564)
- [x] make the table manage provision current table with one read capacity, old tables with different. (#257)
- [x] add a histogram of write rate per hash (#261)
- [x] add flush rate graph somewhere (https://github.com/weaveworks/monitoring/pull/144)
- [x] move label name to hash key (#262)
- [x] stop reading 2x due to base64 encoding (#262)
- [x] shard flush queues in ingesters by hash key (#271)

Noticed when deploying to prod.  Slack logs:

```
[11:14 AM]  
tom hmm cortex in prod seems unhealthy: https://cloud.weave.works/admin/grafana/dashboard/file/cortex-chunks.json?panelId=6&fullscreen&from=1485746034561&to=1485861234561
huge flush queue

[11:14 AM]  
tom 6 chunks per series
massive backlog
we should have an alert for this...
in the meantime, I’m going to up the dynamodb capacity to see if that helps

[11:15 AM]  
jml do we have any way of measuring for hotspotting?

[11:16 AM]  
tom not really
turned off table manager for now
Okay our graphs aren’t wrong:
From amazon
```

<img width="557" alt="screen shot 2017-01-31 at 11 19 07" src="https://cloud.githubusercontent.com/assets/444037/22463908/4566c184-e7ac-11e6-919f-1787573d0685.png">

```
[11:19 AM]  
tom no where near provisioned capacity
upped by 3x to 15k
this is the thing to reread: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GuidelinesForTables.html#GuidelinesForTables.Partitions
> A single partition can support a maximum of 3,000 read capacity units or 1,000 write capacity units
since we’re seeing about 1k writes, I guess thats it
> A single partition can hold approximately 10 GB of data
a week for us is about 50GB
so we’re at about 5 shards (5k write throughout, 50GB data)
and we’re not getting balance....
ridiculous
so this flush is clearly going to fail
that doesn’t mean we’ll loose data
as its replicated, and only one ingester is flushing
the deployment will stop after one ingester fails
to give us some time to figure this out
this has been going on since friday 27th
interesting
```

<img width="443" alt="screen shot 2017-01-31 at 11 33 16" src="https://cloud.githubusercontent.com/assets/444037/22463947/6cf005c6-e7ac-11e6-847e-72c8ce5d8b5b.png">

```
[11:33 AM]  
tom effect of daily buckets
at midnight, a bunch of chunks have to be written to both buckets
so on thursday at midnight we moved to a new table
and ever since then, we’ve been failing to flush
actually our flush rate seems to have been okay, this does seem to just be load from users
right I think I might have a hypothesis
I think they’re stuck flushing to an old table
that we’ve reduced to 1 qps
```

**Comment by tomwilkie** [comment]
Running theory is/was that the ingesters were “stuck” flushing a chunk to last weeks table, however this graph seems to disprove that:

<img width="943" alt="screen shot 2017-01-31 at 12 24 58" src="https://cloud.githubusercontent.com/assets/444037/22464847/c7a70b00-e7b0-11e6-9268-33fc391c7547.png">

**Comment by tomwilkie** [comment]
Also worth noting only two ingesters seem "stuck" in prod (but all are in dev):

<img width="402" alt="screen shot 2017-01-31 at 12 27 50" src="https://cloud.githubusercontent.com/assets/444037/22464861/d8d4bb16-e7b0-11e6-9449-3705e3a05cc6.png">

**Comment by tomwilkie** [comment]
Things we should do to help:
- [ ] add table name as dimension to the the dynamodb errors metrics
- [ ] limit number of retries for chunk flush on provisioned throughput errors

**Comment by tomwilkie** [comment]
Those two ingesters have very high s3 latency:

<img width="1271" alt="screen shot 2017-01-31 at 13 35 34" src="https://cloud.githubusercontent.com/assets/444037/22466937/7c7d1d86-e7ba-11e6-82b9-31947ef2934d.png">

**Comment by tomwilkie** [comment]
I think s3 latency was a red herring - those instances were doing more writes.

We're also seeing this on dev.  Took a stack dump (https://gist.github.com/tomwilkie/a1159d8974d231965fd04a6c26d0105b) and all the flush goroutines were in backoff sleeps.

Upped read throughput on dev to match write throughput, and progress started to be made:

<img width="610" alt="screen shot 2017-01-31 at 15 27 51" src="https://cloud.githubusercontent.com/assets/444037/22471892/c3e906c4-e7cb-11e6-8c81-52f4a58368c0.png">

Have upped read throughput on prod to match.

**Comment by tomwilkie** [comment]
Looks like this might be self-inflicted - flux has some very high cardinality metrics (see https://github.com/weaveworks/flux/issues/417)

**Comment by jml** [comment]
Still happening even though we've disabled flux scraping.

**Comment by tomwilkie** [comment]
The error was `ResourceNotFoundException`, which indicated the table we're writing too didn't exist.  This is because I had turned down the table manage so I could tweak the tables manually.  I have turned it back up, and it is flushing again.

**Comment by tomwilkie** [comment]
This is resolve in dev, will deploy to prod tomorrow:

<img width="1277" alt="screen shot 2017-02-08 at 10 30 57" src="https://cloud.githubusercontent.com/assets/444037/22753496/31d347c6-ee34-11e6-9e7a-46c31b5821f7.png">

**Comment by tomwilkie** [comment]
This is in prod now.
