### ISSUE TITLE
Post merge reviews

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/cortex#97]
Tracking ticket for stuff that didn't get a proper review:

## Day 1

- [x] #96 
- [x] #93 
- [x] #98 
- [x] #99 
- [x] weaveworks/monitoring#26
- [x] weaveworks/monitoring#27
- [x] weaveworks/service-conf#322
- [x] #102 
- [x] #103 
- [x] weaveworks/monitoring#29
- [x] #104 
- [x] weaveworks/monitoring#31
- [x] #106 
- [x] #107 

## Day 2

- [x] #117 — Use age of oldest chunk when deciding to flush 
- [x] #118 — Make max chunk size
- [x] #119 — Remove chunk store parallelisation; add backoff
- [x] #116 — Parameterise the number of concurrent flushers

## Day 3

- [x] https://github.com/weaveworks/service-conf/issues/329
- [x] https://github.com/weaveworks/service-conf/issues/332
- [x] https://github.com/weaveworks/service-conf/issues/338
- [x] https://github.com/weaveworks/service-conf/issues/340
- [x] https://github.com/weaveworks/service-conf/issues/341
- [x] https://github.com/weaveworks/cortex/issues/124
- [x] https://github.com/weaveworks/cortex/issues/131
- [x] https://github.com/weaveworks/monitoring/issues/48
- [x] https://github.com/weaveworks/cortex/issues/134
- [x] https://github.com/weaveworks/cortex/issues/137
- [x] https://github.com/weaveworks/cortex/issues/138
- [x] https://github.com/weaveworks/monitoring/issues/50

**Comment by jml** [comment]
All issues reviewed. Closing optimistically ;)

**Comment by jml** [comment]
Post-merge reviews done. Let's not do any more of these.

**Comment by tomwilkie** [comment]
Agreed!
